In [34]:
#no cmd

# pip3 install numpy

# show numpy


import numpy


In [4]:
a = numpy.array([10,20,30,40])
type(a)

numpy.ndarray

In [10]:
mat = numpy.array([[1,2], [3,4]])
mat

array([[1, 2],
       [3, 4]])

In [14]:
print(mat[1][1])
print(mat[-1][-1])


4
4


In [16]:
mat[1,:]
# acessar 1 array por linha

array([3, 4])

In [18]:
# acessar array na primeira coluna
mat[:,0]

array([1, 3])

In [22]:
mat.transpose()
# transformar linhas em colunas, e colunas em linhas

array([[1, 3],
       [2, 4]])

In [28]:
m1 = numpy.array([[1,2], [3,4]])
m2 = numpy.array([[5,6], [7,8]])
m1 + m2
#adção de matriz

#subtração
m1 - m2

# multiplicação (numero de linhas tem que ser igual numero de colunas)

array([[-4, -4],
       [-4, -4]])

In [33]:
#obter o indice do marior valor do array
m3 = numpy.array([1,2,3,4])
m3.argmax()

#obter o indice do menor valor do array
m3 = numpy.array([1,2,3,4])
m3.argmin()

0